-- Reference data required in every environment, so it lives in a migration rather than
-- supabase/seed.sql (db push promotes migrations only). All inserts are idempotent, so
-- `db reset` and re-pushes are safe.
--
-- The weather_codes block is generated by `python3 -m app.weather_codes` — regenerate it
-- there rather than editing by hand; app/weather_codes.py is the single source of truth.

insert into public.weather_codes (code, description) values
  (0, 'Clear sky'),
  (1, 'Mainly clear'),
  (2, 'Partly cloudy'),
  (3, 'Overcast'),
  (45, 'Fog'),
  (48, 'Depositing rime fog'),
  (51, 'Light drizzle'),
  (53, 'Moderate drizzle'),
  (55, 'Dense drizzle'),
  (56, 'Light freezing drizzle'),
  (57, 'Dense freezing drizzle'),
  (61, 'Slight rain'),
  (63, 'Moderate rain'),
  (65, 'Heavy rain'),
  (66, 'Light freezing rain'),
  (67, 'Heavy freezing rain'),
  (71, 'Slight snow fall'),
  (73, 'Moderate snow fall'),
  (75, 'Heavy snow fall'),
  (77, 'Snow grains'),
  (80, 'Slight rain showers'),
  (81, 'Moderate rain showers'),
  (82, 'Violent rain showers'),
  (85, 'Slight snow showers'),
  (86, 'Heavy snow showers'),
  (95, 'Thunderstorm'),
  (96, 'Thunderstorm with slight hail'),
  (99, 'Thunderstorm with heavy hail')
on conflict (code) do update set description = excluded.description;

-- Coordinates verified against Open-Meteo's geocoding API; all America/Denver.
insert into public.locations (name, latitude, longitude) values
  ('Denver',            39.73915, -104.98470),
  ('Colorado Springs',  38.83388, -104.82136),
  ('Pueblo',            38.25445, -104.60914),
  ('Leadville',         39.25082, -106.29252),
  ('Fort Collins',      40.58526, -105.08442),
  ('Durango',           37.27528, -107.88007),
  ('Grand Junction',    39.06387, -108.55065),
  ('Glenwood Springs',  39.55054, -107.32478),
  ('Steamboat Springs', 40.48498, -106.83172),
  ('Castle Rock',       39.37221, -104.85609),
  ('Longmont',          40.16721, -105.10193),
  ('Boulder',           40.01499, -105.27055)
on conflict (name) do update set
  latitude = excluded.latitude,
  longitude = excluded.longitude;
